services:
  database:
    image: "postgres:latest"
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env
    volumes:
      - db-data:/var/lib/postgresql
      - ./backend/db_create.sql:/docker-entrypoint-initdb.d/db_create.sql:ro
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:8080"
    env_file:
      - ./backend/.env
    depends_on:
      - database
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  db-data: